import {
  ALL_PAST_COUNCIL_TAB,
  ALL_PENDING_COUNCIL_TAB,
  BgCouncilDdForms,
  MavenCouncilDdForms,
  MY_PAST_COUNCIL_TAB,
  MY_PENDING_COUNCIL_TAB,
  UPDATE_USER_COUNCIL_PROFILE_FORM,
} from 'pages/Council/helpers/council.consts'
import {
  ADD_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  ADD_COUNCIL_MEMBER_ACTION,
  ADD_VESTEE_ACTION,
  CHANGE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  CHANGE_COUNCIL_MEMBER_ACTION,
  COUNCIL_ACTIONS_PARAMS_MAPPER,
  DROP_BREAK_GLASS_COUNCIL_REQUEST_ACTION,
  DROP_FIN_REQUEST_ACTION,
  DROP_MAVEN_COUNCIL_REQUEST_ACTION,
  PROPAGATE_BREAK_GLASS_ACTION,
  REMOVE_BG_CONTROL_ACTION,
  REMOVE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  REMOVE_COUNCIL_MEMBER_ACTION,
  REMOVE_VESTEE_ACTION,
  REQUEST_TOKENS_ACTION,
  REQUEST_TOKENS_MINT_ACTION,
  SET_BAKER_ACTION,
  SET_CONTRACT_BAKER_ACTION,
  SET_SELECTED_CONTRACTS_ADMIN_ACTION,
  SIGN_BREAK_GLASS_COUNCIL_ACTION,
  SIGN_MAVEN_COUNCIL_ACTION,
  TOGGLE_VESTEE_LOCK_ACTION,
  TRANSFER_TOKENS_ACTION,
  UNPAUSE_ALL_ENTRYPOINTS_ACTION,
  UPDATE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  UPDATE_COUNCIL_MEMBER_INFO_ACTION,
  UPDATE_VESTEE_ACTION,
} from './council.consts'
import { getClientActionIdByIndexerActionType } from './council.utils'

export type BreakGlassCouncilActions =
  | typeof SET_SELECTED_CONTRACTS_ADMIN_ACTION
  | typeof ADD_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof CHANGE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof REMOVE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof SIGN_BREAK_GLASS_COUNCIL_ACTION
  | typeof UPDATE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof PROPAGATE_BREAK_GLASS_ACTION
  | typeof DROP_BREAK_GLASS_COUNCIL_REQUEST_ACTION
  | typeof UNPAUSE_ALL_ENTRYPOINTS_ACTION
  | typeof REMOVE_BG_CONTROL_ACTION

export type MavrykCouncilActions =
  | typeof SIGN_MAVEN_COUNCIL_ACTION
  | typeof ADD_VESTEE_ACTION
  | typeof ADD_COUNCIL_MEMBER_ACTION
  | typeof UPDATE_VESTEE_ACTION
  | typeof TOGGLE_VESTEE_LOCK_ACTION
  | typeof CHANGE_COUNCIL_MEMBER_ACTION
  | typeof REMOVE_COUNCIL_MEMBER_ACTION
  | typeof UPDATE_COUNCIL_MEMBER_INFO_ACTION
  | typeof TRANSFER_TOKENS_ACTION
  | typeof REQUEST_TOKENS_ACTION
  | typeof REQUEST_TOKENS_MINT_ACTION
  | typeof DROP_FIN_REQUEST_ACTION
  | typeof REMOVE_VESTEE_ACTION
  | typeof SET_BAKER_ACTION
  | typeof SET_CONTRACT_BAKER_ACTION
  | typeof DROP_MAVEN_COUNCIL_REQUEST_ACTION

export type CouncilTabsType =
  | typeof MY_PENDING_COUNCIL_TAB
  | typeof MY_PAST_COUNCIL_TAB
  | typeof ALL_PENDING_COUNCIL_TAB
  | typeof ALL_PAST_COUNCIL_TAB
  | null

export type CouncilsFormsIds =
  | (typeof MavenCouncilDdForms)[keyof typeof MavenCouncilDdForms]
  | (typeof BgCouncilDdForms)[keyof typeof BgCouncilDdForms]
  | typeof UPDATE_USER_COUNCIL_PROFILE_FORM

// NonNullable cuz we filter null actions in normalizer
export type CouncilsActionsIds = NonNullable<ReturnType<typeof getClientActionIdByIndexerActionType>>

export type CouncilActionParamsNames =
  (typeof COUNCIL_ACTIONS_PARAMS_MAPPER)[keyof typeof COUNCIL_ACTIONS_PARAMS_MAPPER]
