import {
  MY_PENDING_COUNSIL_TAB,
  MY_PAST_COUNSIL_TAB,
  ALL_PENDING_COUNSIL_TAB,
  ALL_PAST_COUNSIL_TAB,
  BgCounsilDdForms,
  MavrykCounsilDdForms,
  UPDATE_USER_COUNCIL_PROFILE_FORM,
} from 'pages/Council/helpers/council.consts'
import {
  ADD_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  CHANGE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  DROP_BREAK_GLASS_COUNCIL_REQUEST_ACTION,
  PROPAGATE_BREAK_GLASS_ACTION,
  REMOVE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  SET_SELECTED_CONTRACTS_ADMIN_ACTION,
  SIGN_BREAK_GLASS_COUNCIL_ACTION,
  UPDATE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  SIGN_MAVRYK_COUNCIL_ACTION,
  ADD_VESTEE_ACTION,
  ADD_COUNSIL_MEMBER_ACTION,
  UPDATE_VESTEE_ACTION,
  TOGGLE_VESTEE_LOCK_ACTION,
  CHANGE_COUNCIL_MEMBER_ACTION,
  REMOVE_COUNCIL_MEMBER_ACTION,
  UPDATE_COUNSIL_MEMBER_INFO_ACTION,
  TRANSFER_TOKENS_ACTION,
  REQUEST_TOKENS_ACTION,
  REQUEST_TOKENS_MINT_ACTION,
  DROP_FIN_REQUEST_ACTION,
  REMOVE_VESTEE_ACTION,
  SET_BAKER_ACTION,
  SET_CONTRACT_BAKER_ACTION,
  DROP_MAVRYK_COUNCIL_REQUEST_ACTION,
  REMOVE_BG_CONTROLL_ACTION,
  UNPAUSE_ALL_ENTRYPOINTS_ACTION,
  COUNCIL_ACTIONS_PARAMS_MAPPER,
} from './council.consts'
import { getClientActionIdByIndexerActionType } from './council.utils'

export type BreakGlassCouncilActions =
  | typeof SET_SELECTED_CONTRACTS_ADMIN_ACTION
  | typeof ADD_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof CHANGE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof REMOVE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof SIGN_BREAK_GLASS_COUNCIL_ACTION
  | typeof UPDATE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof PROPAGATE_BREAK_GLASS_ACTION
  | typeof DROP_BREAK_GLASS_COUNCIL_REQUEST_ACTION
  | typeof UNPAUSE_ALL_ENTRYPOINTS_ACTION
  | typeof REMOVE_BG_CONTROLL_ACTION

export type MavrykCouncilActions =
  | typeof SIGN_MAVRYK_COUNCIL_ACTION
  | typeof ADD_VESTEE_ACTION
  | typeof ADD_COUNSIL_MEMBER_ACTION
  | typeof UPDATE_VESTEE_ACTION
  | typeof TOGGLE_VESTEE_LOCK_ACTION
  | typeof CHANGE_COUNCIL_MEMBER_ACTION
  | typeof REMOVE_COUNCIL_MEMBER_ACTION
  | typeof UPDATE_COUNSIL_MEMBER_INFO_ACTION
  | typeof TRANSFER_TOKENS_ACTION
  | typeof REQUEST_TOKENS_ACTION
  | typeof REQUEST_TOKENS_MINT_ACTION
  | typeof DROP_FIN_REQUEST_ACTION
  | typeof REMOVE_VESTEE_ACTION
  | typeof SET_BAKER_ACTION
  | typeof SET_CONTRACT_BAKER_ACTION
  | typeof DROP_MAVRYK_COUNCIL_REQUEST_ACTION

export type CouncilTabsType =
  | typeof MY_PENDING_COUNSIL_TAB
  | typeof MY_PAST_COUNSIL_TAB
  | typeof ALL_PENDING_COUNSIL_TAB
  | typeof ALL_PAST_COUNSIL_TAB
  | null

export type CouncilsFormsIds =
  | (typeof MavrykCounsilDdForms)[keyof typeof MavrykCounsilDdForms]
  | (typeof BgCounsilDdForms)[keyof typeof BgCounsilDdForms]
  | typeof UPDATE_USER_COUNCIL_PROFILE_FORM

// NonNullable cuz we filter null actions in normalizer
export type CouncilsActionsIds = NonNullable<ReturnType<typeof getClientActionIdByIndexerActionType>>

export type CouncilActionParamsNames =
  (typeof COUNCIL_ACTIONS_PARAMS_MAPPER)[keyof typeof COUNCIL_ACTIONS_PARAMS_MAPPER]
