import {
  ADD_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  CHANGE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  DROP_BREAK_GLASS_ACTION,
  PROPAGATE_BREAK_GLASS_ACTION,
  REMOVE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
  SET_ALL_CONTRACTS_ADMIN_ACTION,
  SET_SINGLE_CONTRACT_ADMIN_ACTION,
  SIGN_BREAK_GLASS_ACTION,
  UPDATE_BREAK_GLASS_COUNCIL_MEMBER_ACTION,
} from './council.consts'

export type BreakGlassCouncilActions =
  | typeof SET_ALL_CONTRACTS_ADMIN_ACTION
  | typeof SET_SINGLE_CONTRACT_ADMIN_ACTION
  | typeof ADD_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof CHANGE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof REMOVE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof SIGN_BREAK_GLASS_ACTION
  | typeof UPDATE_BREAK_GLASS_COUNCIL_MEMBER_ACTION
  | typeof PROPAGATE_BREAK_GLASS_ACTION
  | typeof DROP_BREAK_GLASS_ACTION
