/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\nquery getMaxlenghtsQuery {\n    council {\n      council_member_image_max_length\n      council_member_name_max_length\n      council_member_website_max_length\n      request_purpose_max_length\n      request_token_name_max_length\n    }\n    governance {\n      proposal_description_max_length\n      proposal_invoice_max_length\n      proposal_metadata_title_max_length\n      proposal_source_code_max_length\n      proposal_title_max_length\n    }\n    emergency_governance {\n      proposal_desc_max_length\n      proposal_title_max_length\n    }\n    governance_satellite {\n      gov_purpose_max_length\n    }\n    delegation {\n      satellite_description_max_length\n      satellite_name_max_length\n      satellite_website_max_length\n    }\n  }\n  \n": types.GetMaxlenghtsQueryDocument,
    "\n  subscription FeedsRewardsAmountSubscription {\n    aggregator_aggregate {\n      aggregate {\n        sum {\n          reward_amount_smvk\n        }\n      }\n    }\n  }\n": types.FeedsRewardsAmountSubscriptionDocument,
    "\n  subscription subsribeOracleDataFeed {\n    aggregator(where: { admin: { _neq: \"\" } }, order_by: { creation_timestamp: desc }) {\n      address\n      admin\n      decimals\n      factory {\n        address\n      }\n      history_data(distinct_on: timestamp, order_by: { timestamp: desc }) {\n        data\n        timestamp\n        aggregator {\n          decimals\n        }\n      }\n      metadata\n      network\n      creation_timestamp\n      last_completed_data\n      last_completed_data_last_updated_at\n      last_completed_data_pct_oracle_resp\n      last_updated_at\n      heart_beat_seconds\n      name\n      reward_amount_xtz\n      reward_amount_smvk\n      pct_oracle_threshold\n      alpha_pct_per_thousand\n      heart_beat_seconds\n      oracles {\n        observations {\n          epoch\n          round\n          timestamp\n          oracle {\n            user_id\n            init_epoch\n            init_round\n          }\n        }\n      }\n    }\n  }\n": types.SubsribeOracleDataFeedDocument,
    "\nsubscription getLendingDiff($currentTimestamp: timestamptz) {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}, timestamp: {_gte: $currentTimestamp}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        token {\n          token_address\n        }\n      }\n    }\n  \n    loan_tokens {\n      total_borrowed\n      token_pool_total\n      token {\n        token_address\n      }\n    }\n  }\n}\n": types.GetLendingDiffDocument,
    "\nsubscription getLoansHistoryData {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        loan_token_name\n        token {\n          token_address\n        }\n      }\n      collateral_token {\n        token {\n          token_address\n        }\n      }\n    }\n  }\n}\n": types.GetLoansHistoryDataDocument,
    "\nsubscription getLoansHistoryForMarketData($marketTokenAddress: String, $userAddress: String) {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}, loan_token: {token: {token_address: {_eq: $marketTokenAddress}}}, sender: {address: {_eq: $userAddress}}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        loan_token_name\n        token {\n          token_address\n        }\n      }\n      collateral_token {\n        token {\n          token_address\n        }\n      }\n      operation_hash\n      sender {\n        address\n      }\n      vault {\n        vault {\n          address\n        }\n      }\n    }\n  }\n}\n": types.GetLoansHistoryForMarketDataDocument,
    "\n  subscription subscribeSmvkHistoryData {\n    smvk_history_data(distinct_on: timestamp) {\n      mvk_total_supply\n      smvk_total_supply\n      timestamp\n    }\n  }\n": types.SubscribeSmvkHistoryDataDocument,
    "\n  subscription subscribeAdressBalance($_eq: String) {\n    mavryk_user(where: { address: { _eq: $_eq } }) {\n      address\n      mvk_balance\n      smvk_balance\n    }\n  }\n": types.SubscribeAdressBalanceDocument,
    "\nsubscription subscribeMvkTokenTotal {\n  mvk_token {\n    total_supply\n    maximum_supply\n  }\n}\n": types.SubscribeMvkTokenTotalDocument,
    "\nquery MVKFaucet {\n  mvk_faucet{\n    address\n  }\n}\n": types.MvkFaucetDocument,
    "\n  subscription tokensMetadata {\n    token {\n      token_id\n      metadata\n      token_address\n      token_standard\n\n      # check whether tokens is collateral token\n      lending_controller_collateral_tokens {\n        token_name\n        protected\n      }\n\n      # check whether tokens is loan token\n      lending_controller_loan_tokens {\n        loan_token_name\n      }\n\n      # check whether tokens is mToken\n      m_tokens {\n        address\n      }\n\n      # check that it's real MVK token\n      mvk_tokens {\n        address\n      }\n    }\n  }\n": types.TokensMetadataDocument,
    "\n  subscription getUserLoansData($userAddress: String = \"\", $_in: [smallint!] = [\"0\", \"1\", \"2\", \"3\"]) {\n    mavryk_user(where: { address: { _eq: $userAddress } }) {\n      lending_controller_history_data_sender(\n        where: { lending_controller: { mock_time: { _eq: false } }, type: { _in: $_in } }\n        order_by: { type: asc, timestamp: asc }\n      ) {\n\t\t\t\tid\n        type\n        timestamp\n        operation_hash\n        amount\n        loan_token {\n          token {\n            token_address\n          }\n          current_interest_rate\n        }\n        lending_controller {\n          interest_rate_decimals\n          interest_treasury_share\n          decimals\n        }\n      }\n\n      lending_controller_vaults(where: { lending_controller: { mock_time: { _eq: false } } }) {\n        collateral_balances {\n          balance\n          collateral_token {\n            token {\n              token_address\n            }\n          }\n        }\n        loan_decimals\n        loan_principal_total\n        loan_token {\n          token {\n            token_address\n          }\n        }\n      }\n    }\n  }\n": types.GetUserLoansDataDocument,
    "\nsubscription getUserMvkSmvkBalance($userAddress: String = \"tz1Y2tUUooW6QT6pQCeqz9ep9wCkX5bnKeTs\") {\n\tmavryk_user(where: {address: {_eq: $userAddress}}) {\n  \tsmvk_balance\n    mvk_balance\n\n\t\t# TODO: check how to get address, usage of mvk_transfer_sender & mvk_transfer_receiver is temp\n    mvk_transfer_sender(limit: 1) {\n      mvk_token {\n        address\n      }\n    }\n    mvk_transfer_receiver(limit: 1) {\n      mvk_token {\n        address\n      }\n    }\n\n\t\t# Getting user mToken balances\n\t\tm_token_accounts {\n      balance\n      m_token {\n        address\n      }\n    }\n\t}\n}\n": types.GetUserMvkSmvkBalanceDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nquery getMaxlenghtsQuery {\n    council {\n      council_member_image_max_length\n      council_member_name_max_length\n      council_member_website_max_length\n      request_purpose_max_length\n      request_token_name_max_length\n    }\n    governance {\n      proposal_description_max_length\n      proposal_invoice_max_length\n      proposal_metadata_title_max_length\n      proposal_source_code_max_length\n      proposal_title_max_length\n    }\n    emergency_governance {\n      proposal_desc_max_length\n      proposal_title_max_length\n    }\n    governance_satellite {\n      gov_purpose_max_length\n    }\n    delegation {\n      satellite_description_max_length\n      satellite_name_max_length\n      satellite_website_max_length\n    }\n  }\n  \n"): (typeof documents)["\nquery getMaxlenghtsQuery {\n    council {\n      council_member_image_max_length\n      council_member_name_max_length\n      council_member_website_max_length\n      request_purpose_max_length\n      request_token_name_max_length\n    }\n    governance {\n      proposal_description_max_length\n      proposal_invoice_max_length\n      proposal_metadata_title_max_length\n      proposal_source_code_max_length\n      proposal_title_max_length\n    }\n    emergency_governance {\n      proposal_desc_max_length\n      proposal_title_max_length\n    }\n    governance_satellite {\n      gov_purpose_max_length\n    }\n    delegation {\n      satellite_description_max_length\n      satellite_name_max_length\n      satellite_website_max_length\n    }\n  }\n  \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription FeedsRewardsAmountSubscription {\n    aggregator_aggregate {\n      aggregate {\n        sum {\n          reward_amount_smvk\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription FeedsRewardsAmountSubscription {\n    aggregator_aggregate {\n      aggregate {\n        sum {\n          reward_amount_smvk\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription subsribeOracleDataFeed {\n    aggregator(where: { admin: { _neq: \"\" } }, order_by: { creation_timestamp: desc }) {\n      address\n      admin\n      decimals\n      factory {\n        address\n      }\n      history_data(distinct_on: timestamp, order_by: { timestamp: desc }) {\n        data\n        timestamp\n        aggregator {\n          decimals\n        }\n      }\n      metadata\n      network\n      creation_timestamp\n      last_completed_data\n      last_completed_data_last_updated_at\n      last_completed_data_pct_oracle_resp\n      last_updated_at\n      heart_beat_seconds\n      name\n      reward_amount_xtz\n      reward_amount_smvk\n      pct_oracle_threshold\n      alpha_pct_per_thousand\n      heart_beat_seconds\n      oracles {\n        observations {\n          epoch\n          round\n          timestamp\n          oracle {\n            user_id\n            init_epoch\n            init_round\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription subsribeOracleDataFeed {\n    aggregator(where: { admin: { _neq: \"\" } }, order_by: { creation_timestamp: desc }) {\n      address\n      admin\n      decimals\n      factory {\n        address\n      }\n      history_data(distinct_on: timestamp, order_by: { timestamp: desc }) {\n        data\n        timestamp\n        aggregator {\n          decimals\n        }\n      }\n      metadata\n      network\n      creation_timestamp\n      last_completed_data\n      last_completed_data_last_updated_at\n      last_completed_data_pct_oracle_resp\n      last_updated_at\n      heart_beat_seconds\n      name\n      reward_amount_xtz\n      reward_amount_smvk\n      pct_oracle_threshold\n      alpha_pct_per_thousand\n      heart_beat_seconds\n      oracles {\n        observations {\n          epoch\n          round\n          timestamp\n          oracle {\n            user_id\n            init_epoch\n            init_round\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nsubscription getLendingDiff($currentTimestamp: timestamptz) {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}, timestamp: {_gte: $currentTimestamp}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        token {\n          token_address\n        }\n      }\n    }\n  \n    loan_tokens {\n      total_borrowed\n      token_pool_total\n      token {\n        token_address\n      }\n    }\n  }\n}\n"): (typeof documents)["\nsubscription getLendingDiff($currentTimestamp: timestamptz) {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}, timestamp: {_gte: $currentTimestamp}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        token {\n          token_address\n        }\n      }\n    }\n  \n    loan_tokens {\n      total_borrowed\n      token_pool_total\n      token {\n        token_address\n      }\n    }\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nsubscription getLoansHistoryData {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        loan_token_name\n        token {\n          token_address\n        }\n      }\n      collateral_token {\n        token {\n          token_address\n        }\n      }\n    }\n  }\n}\n"): (typeof documents)["\nsubscription getLoansHistoryData {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        loan_token_name\n        token {\n          token_address\n        }\n      }\n      collateral_token {\n        token {\n          token_address\n        }\n      }\n    }\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nsubscription getLoansHistoryForMarketData($marketTokenAddress: String, $userAddress: String) {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}, loan_token: {token: {token_address: {_eq: $marketTokenAddress}}}, sender: {address: {_eq: $userAddress}}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        loan_token_name\n        token {\n          token_address\n        }\n      }\n      collateral_token {\n        token {\n          token_address\n        }\n      }\n      operation_hash\n      sender {\n        address\n      }\n      vault {\n        vault {\n          address\n        }\n      }\n    }\n  }\n}\n"): (typeof documents)["\nsubscription getLoansHistoryForMarketData($marketTokenAddress: String, $userAddress: String) {\n  lending_controller(where: {mock_time: {_eq: false}}) {\n    history_data(where: {type: {_in: [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"]}, loan_token: {token: {token_address: {_eq: $marketTokenAddress}}}, sender: {address: {_eq: $userAddress}}}, distinct_on: timestamp, order_by: {timestamp: asc}) {\n      type\n      amount\n      timestamp\n      loan_token {\n        loan_token_name\n        token {\n          token_address\n        }\n      }\n      collateral_token {\n        token {\n          token_address\n        }\n      }\n      operation_hash\n      sender {\n        address\n      }\n      vault {\n        vault {\n          address\n        }\n      }\n    }\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription subscribeSmvkHistoryData {\n    smvk_history_data(distinct_on: timestamp) {\n      mvk_total_supply\n      smvk_total_supply\n      timestamp\n    }\n  }\n"): (typeof documents)["\n  subscription subscribeSmvkHistoryData {\n    smvk_history_data(distinct_on: timestamp) {\n      mvk_total_supply\n      smvk_total_supply\n      timestamp\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription subscribeAdressBalance($_eq: String) {\n    mavryk_user(where: { address: { _eq: $_eq } }) {\n      address\n      mvk_balance\n      smvk_balance\n    }\n  }\n"): (typeof documents)["\n  subscription subscribeAdressBalance($_eq: String) {\n    mavryk_user(where: { address: { _eq: $_eq } }) {\n      address\n      mvk_balance\n      smvk_balance\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nsubscription subscribeMvkTokenTotal {\n  mvk_token {\n    total_supply\n    maximum_supply\n  }\n}\n"): (typeof documents)["\nsubscription subscribeMvkTokenTotal {\n  mvk_token {\n    total_supply\n    maximum_supply\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nquery MVKFaucet {\n  mvk_faucet{\n    address\n  }\n}\n"): (typeof documents)["\nquery MVKFaucet {\n  mvk_faucet{\n    address\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription tokensMetadata {\n    token {\n      token_id\n      metadata\n      token_address\n      token_standard\n\n      # check whether tokens is collateral token\n      lending_controller_collateral_tokens {\n        token_name\n        protected\n      }\n\n      # check whether tokens is loan token\n      lending_controller_loan_tokens {\n        loan_token_name\n      }\n\n      # check whether tokens is mToken\n      m_tokens {\n        address\n      }\n\n      # check that it's real MVK token\n      mvk_tokens {\n        address\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription tokensMetadata {\n    token {\n      token_id\n      metadata\n      token_address\n      token_standard\n\n      # check whether tokens is collateral token\n      lending_controller_collateral_tokens {\n        token_name\n        protected\n      }\n\n      # check whether tokens is loan token\n      lending_controller_loan_tokens {\n        loan_token_name\n      }\n\n      # check whether tokens is mToken\n      m_tokens {\n        address\n      }\n\n      # check that it's real MVK token\n      mvk_tokens {\n        address\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  subscription getUserLoansData($userAddress: String = \"\", $_in: [smallint!] = [\"0\", \"1\", \"2\", \"3\"]) {\n    mavryk_user(where: { address: { _eq: $userAddress } }) {\n      lending_controller_history_data_sender(\n        where: { lending_controller: { mock_time: { _eq: false } }, type: { _in: $_in } }\n        order_by: { type: asc, timestamp: asc }\n      ) {\n\t\t\t\tid\n        type\n        timestamp\n        operation_hash\n        amount\n        loan_token {\n          token {\n            token_address\n          }\n          current_interest_rate\n        }\n        lending_controller {\n          interest_rate_decimals\n          interest_treasury_share\n          decimals\n        }\n      }\n\n      lending_controller_vaults(where: { lending_controller: { mock_time: { _eq: false } } }) {\n        collateral_balances {\n          balance\n          collateral_token {\n            token {\n              token_address\n            }\n          }\n        }\n        loan_decimals\n        loan_principal_total\n        loan_token {\n          token {\n            token_address\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription getUserLoansData($userAddress: String = \"\", $_in: [smallint!] = [\"0\", \"1\", \"2\", \"3\"]) {\n    mavryk_user(where: { address: { _eq: $userAddress } }) {\n      lending_controller_history_data_sender(\n        where: { lending_controller: { mock_time: { _eq: false } }, type: { _in: $_in } }\n        order_by: { type: asc, timestamp: asc }\n      ) {\n\t\t\t\tid\n        type\n        timestamp\n        operation_hash\n        amount\n        loan_token {\n          token {\n            token_address\n          }\n          current_interest_rate\n        }\n        lending_controller {\n          interest_rate_decimals\n          interest_treasury_share\n          decimals\n        }\n      }\n\n      lending_controller_vaults(where: { lending_controller: { mock_time: { _eq: false } } }) {\n        collateral_balances {\n          balance\n          collateral_token {\n            token {\n              token_address\n            }\n          }\n        }\n        loan_decimals\n        loan_principal_total\n        loan_token {\n          token {\n            token_address\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\nsubscription getUserMvkSmvkBalance($userAddress: String = \"tz1Y2tUUooW6QT6pQCeqz9ep9wCkX5bnKeTs\") {\n\tmavryk_user(where: {address: {_eq: $userAddress}}) {\n  \tsmvk_balance\n    mvk_balance\n\n\t\t# TODO: check how to get address, usage of mvk_transfer_sender & mvk_transfer_receiver is temp\n    mvk_transfer_sender(limit: 1) {\n      mvk_token {\n        address\n      }\n    }\n    mvk_transfer_receiver(limit: 1) {\n      mvk_token {\n        address\n      }\n    }\n\n\t\t# Getting user mToken balances\n\t\tm_token_accounts {\n      balance\n      m_token {\n        address\n      }\n    }\n\t}\n}\n"): (typeof documents)["\nsubscription getUserMvkSmvkBalance($userAddress: String = \"tz1Y2tUUooW6QT6pQCeqz9ep9wCkX5bnKeTs\") {\n\tmavryk_user(where: {address: {_eq: $userAddress}}) {\n  \tsmvk_balance\n    mvk_balance\n\n\t\t# TODO: check how to get address, usage of mvk_transfer_sender & mvk_transfer_receiver is temp\n    mvk_transfer_sender(limit: 1) {\n      mvk_token {\n        address\n      }\n    }\n    mvk_transfer_receiver(limit: 1) {\n      mvk_token {\n        address\n      }\n    }\n\n\t\t# Getting user mToken balances\n\t\tm_token_accounts {\n      balance\n      m_token {\n        address\n      }\n    }\n\t}\n}\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;