export const SATELLITE_LEDGER_LIST = [
  {
    address: 'tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb',
    description: 'Test Description',
    image: 'https://www.numerama.com/wp-content/uploads/2020/09/never-gonna-give-you-up-clip.jpg',
    mvkBalance: 24465.114658926,
    sMvkBalance: 534.885341074,
    name: 'Alice Satellite',
    website: 'https://test.il',
    participation: 12,
    registeredDateTime: '2022-03-23T13:55:37.000Z',
    satelliteFee: 0,
    active: true,
    totalDelegatedAmount: 0,
    unregisteredDateTime: '2022-03-23T13:55:37.000Z',
    proposalVotingHistory: [
      {
        id: 1,
        currentRoundVote: false,
        governanceProposalRecordId: 1,
        round: 1,
        timestamp: '2022-03-23T14:01:00.000Z',
        vote: 1,
        voterId: 1,
        votingPower: 500,
        requestData: {
          abstain_mvk_total: 0,
          current_cycle_end_level: 713954,
          current_cycle_start_level: 713939,
          cycle: 1,
          current_round_proposal: false,
          description: 'Test description',
          down_vote_mvk_total: 0,
          executed: true,
          id: 1,
          invoice: 'https://mavryk.finance/',
          locked: true,
        },
      },
    ],
    financialRequestsVotes: [],
  },
  {
    address: 'tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6',
    description: 'Test Description',
    image: 'https://www.numerama.com/wp-content/uploads/2020/09/never-gonna-give-you-up-clip.jpg',
    mvkBalance: 24465.114658926,
    sMvkBalance: 534.885341074,
    name: 'Bob Test',
    website: 'https://test.il',
    participation: 15,
    registeredDateTime: '2022-03-23T13:55:37.000Z',
    satelliteFee: 7,
    active: true,
    totalDelegatedAmount: 15,
    unregisteredDateTime: '2022-03-23T13:55:37.000Z',
    proposalVotingHistory: [
      {
        id: 1,
        currentRoundVote: false,
        governanceProposalRecordId: 1,
        round: 1,
        timestamp: '2022-03-23T14:01:00.000Z',
        vote: 1,
        voterId: 1,
        votingPower: 500,
        requestData: {
          abstain_mvk_total: 0,
          current_cycle_end_level: 713954,
          current_cycle_start_level: 713939,
          cycle: 1,
          current_round_proposal: false,
          description: 'Test description',
          down_vote_mvk_total: 0,
          executed: true,
          id: 1,
          invoice: 'https://mavryk.finance/',
          locked: true,
        },
      },
    ],
    financialRequestsVotes: [],
  },
  {
    address: 'tz1PrFSuTikuSWfZkACrXpmaS4RuKmEcZMSP',
    description: 'Test Description',
    image: 'https://www.numerama.com/wp-content/uploads/2020/09/never-gonna-give-you-up-clip.jpg',
    mvkBalance: 24465.114658926,
    sMvkBalance: 534.885341074,
    name: 'Eve User',
    website: 'https://test.il',
    participation: 7,
    registeredDateTime: '2022-03-23T13:55:37.000Z',
    satelliteFee: 14,
    active: true,
    totalDelegatedAmount: 20,
    unregisteredDateTime: '2022-03-23T13:55:37.000Z',
    proposalVotingHistory: [
      {
        id: 1,
        currentRoundVote: false,
        governanceProposalRecordId: 1,
        round: 1,
        timestamp: '2022-03-23T14:01:00.000Z',
        vote: 1,
        voterId: 1,
        votingPower: 500,
        requestData: {
          abstain_mvk_total: 0,
          current_cycle_end_level: 713954,
          current_cycle_start_level: 713939,
          cycle: 1,
          current_round_proposal: false,
          description: 'Test description',
          down_vote_mvk_total: 0,
          executed: true,
          id: 1,
          invoice: 'https://mavryk.finance/',
          locked: true,
        },
      },
    ],
    financialRequestsVotes: [],
  },
  {
    address: 'tz1TJTq4Rcx4hqCxkGnmwJRpqeDNzoEpjk6n',
    description: 'Test Description',
    image: 'https://www.numerama.com/wp-content/uploads/2020/09/never-gonna-give-you-up-clip.jpg',
    mvkBalance: 24465.114658926,
    sMvkBalance: 534.885341074,
    name: 'Mallory User',
    website: 'https://test.il',
    participation: 7,
    registeredDateTime: '2022-03-23T13:55:37.000Z',
    satelliteFee: 20,
    active: true,
    totalDelegatedAmount: 50,
    unregisteredDateTime: '2022-03-23T13:55:37.000Z',
    proposalVotingHistory: [
      {
        id: 1,
        currentRoundVote: false,
        governanceProposalRecordId: 1,
        round: 1,
        timestamp: '2022-03-23T14:01:00.000Z',
        vote: 1,
        voterId: 1,
        votingPower: 500,
        requestData: {
          abstain_mvk_total: 0,
          current_cycle_end_level: 713954,
          current_cycle_start_level: 713939,
          cycle: 1,
          current_round_proposal: false,
          description: 'Test description',
          down_vote_mvk_total: 0,
          executed: true,
          id: 1,
          invoice: 'https://mavryk.finance/',
          locked: true,
        },
      },
    ],
    financialRequestsVotes: [],
  },
  {
    address: 'qz1VSUr8wwNhLAzempoch5d6hLRiTh8Cj3jb',
    description: 'Test Description',
    image: 'https://www.numerama.com/wp-content/uploads/2020/09/never-gonna-give-you-up-clip.jpg',
    mvkBalance: 24465.114658926,
    sMvkBalance: 534.885341074,
    name: 'Test2 User',
    website: 'https://test.il',
    participation: 7,
    registeredDateTime: '2022-03-23T13:55:37.000Z',
    satelliteFee: 30,
    active: true,
    totalDelegatedAmount: 60,
    unregisteredDateTime: '2022-03-23T13:55:37.000Z',
    proposalVotingHistory: [
      {
        id: 1,
        currentRoundVote: false,
        governanceProposalRecordId: 1,
        round: 1,
        timestamp: '2022-03-23T14:01:00.000Z',
        vote: 1,
        voterId: 1,
        votingPower: 500,
        requestData: {
          abstain_mvk_total: 0,
          current_cycle_end_level: 713954,
          current_cycle_start_level: 713939,
          cycle: 1,
          current_round_proposal: false,
          description: 'Test description',
          down_vote_mvk_total: 0,
          executed: true,
          id: 1,
          invoice: 'https://mavryk.finance/',
          locked: true,
        },
      },
    ],
    financialRequestsVotes: [],
  },
]
