import {
  ADD_COUNCIL_MEMBER_ACTION,
  CHANGE_COUNCIL_MEMBER_ACTION,
  DROP_BREAK_GLASS_ACTION,
  PROPAGATE_BREAK_GLASS_ACTION,
  REMOVE_COUNCIL_MEMBER_ACTION,
  SET_ALL_CONTRACTS_ADMIN_ACTION,
  SET_SINGLE_CONTRACT_ADMIN_ACTION,
  SIGN_ACTION,
  UPDATE_COUNCIL_MEMBER_ACTION,
} from './breakGlassCouncil.consts'

export type BreakGlassCouncilActions =
  | typeof SET_ALL_CONTRACTS_ADMIN_ACTION
  | typeof SET_SINGLE_CONTRACT_ADMIN_ACTION
  | typeof SIGN_ACTION
  | typeof ADD_COUNCIL_MEMBER_ACTION
  | typeof UPDATE_COUNCIL_MEMBER_ACTION
  | typeof CHANGE_COUNCIL_MEMBER_ACTION
  | typeof REMOVE_COUNCIL_MEMBER_ACTION
  | typeof PROPAGATE_BREAK_GLASS_ACTION
  | typeof DROP_BREAK_GLASS_ACTION
