import {
  ADD_ORACLES_AGGREGATOR_ACTION,
  BAN_SATELLITE_ACTION,
  DROP_ACTION,
  FIX_MISTAKEN_TRANSFER_ACTION,
  REGISTER_AGGREGATOR_ACTION,
  REMOVE_ORACLES_ACTION,
  REMOVE_ORACLES_AGGREGATOR_ACTION,
  RESTORE_SATELLITE_ACTION,
  SET_AGGREGATOR_MAINTAINER_ACTION,
  SUSPEND_SATELLITE_ACTION,
  SatelliteGovActionStatus,
  UNBAN_SATELLITE_ACTION,
  UNSUSPEND_SATELLITE_ACTION,
  UPDATE_AGGREGATOR_STATUS_ACTION,
  VOTE_FOR_ACTION,
} from './satellitesGov.consts'

export type SatellitesGovType =
  | typeof SUSPEND_SATELLITE_ACTION
  | typeof UNSUSPEND_SATELLITE_ACTION
  | typeof BAN_SATELLITE_ACTION
  | typeof UNBAN_SATELLITE_ACTION
  | typeof REMOVE_ORACLES_ACTION
  | typeof REMOVE_ORACLES_AGGREGATOR_ACTION
  | typeof ADD_ORACLES_AGGREGATOR_ACTION
  | typeof SET_AGGREGATOR_MAINTAINER_ACTION
  | typeof DROP_ACTION
  | typeof VOTE_FOR_ACTION
  | typeof RESTORE_SATELLITE_ACTION
  | typeof UPDATE_AGGREGATOR_STATUS_ACTION
  | typeof REGISTER_AGGREGATOR_ACTION
  | typeof FIX_MISTAKEN_TRANSFER_ACTION

export type SatelliteGovActionStatusType = (typeof SatelliteGovActionStatus)[keyof typeof SatelliteGovActionStatus]
